spring:
  application:
    name: creatures-service
  datasource:
    url: "jdbc:h2:mem:creatures-db;DB_CLOSE_DELAY=-1;NON_KEYWORDS=YEAR,VALUE"
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    open-in-view: true
    show-sql: true
  sql:
    init:
      mode: always
      platform: h2
  h2:
    console:
      settings:
        trace: false
        web-allow-others: false
server:
  port: 8081

---
#docker
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres1/creatures-db
    driver-class-name: org.postgresql.Driver
    username: user
    password: pwd
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none  #disable or it break
    defer-datasource-initialization: true
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        auto-quote-keyword: true
  sql:
    init:
      mode: always
      platform: psql

server:
#  port: 8080
  port: 8081