spring:
  application:
    name: trainings-service
  datasource:
    url: "jdbc:h2:mem:trainings-db;DB_CLOSE_DELAY=-1;NON_KEYWORDS=YEAR,VALUE"
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    open-in-view: true
    show-sql: true
  sql:
    init:
      mode: always
      platform: h2
  h2:
    console:
      settings:
        trace: false
        web-allow-others: false
server:
  port: 8083
---
#docker
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql2/trainings-db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: pwd
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none  #disable or it break
    defer-datasource-initialization: true
    open-in-view: true
    show-sql: true
  sql:
    init:
      mode: always
      platform: mysql

server:
#  port: 8080
  port: 8083